name: Build The Website

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 0
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Build Website with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload Website to GitHub Artifacts
        uses: actions/upload-pages-artifact@v3
